/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_ioctl_telebot_cli_Console */

#ifndef _Included_cc_ioctl_telebot_cli_Console
#define _Included_cc_ioctl_telebot_cli_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nGetConsoleInfo
 * Signature: ()Lcc/ioctl/telebot/cli/Console/ConsoleInfo;
 */
JNIEXPORT jobject JNICALL Java_cc_ioctl_telebot_cli_Console_nGetConsoleInfo
  (JNIEnv *, jobject);

/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nUpdateStatusText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_telebot_cli_Console_nUpdateStatusText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nUpdateTitleText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_telebot_cli_Console_nUpdateTitleText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nPrintLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_telebot_cli_Console_nPrintLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nLogMessage
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cc_ioctl_telebot_cli_Console_nLogMessage
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     cc_ioctl_telebot_cli_Console
 * Method:    nPromptInputText
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cc_ioctl_telebot_cli_Console_nPromptInputText
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
