/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_ioctl_util_OsUtils */

#ifndef _Included_cc_ioctl_util_OsUtils
#define _Included_cc_ioctl_util_OsUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ioctl_util_OsUtils
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_util_OsUtils_getPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
