# Config file for robot server.
# You MUST obtain your own api_id and api_hash at https://my.telegram.org
# For bot accounts, see file bots.toml

[server]
api_id = 0
api_hash = "xxx"
use_test_dc = false
